[[news]]
date = "2026-05"
content = "搭建个人学术主页，学习 Next.js + TypeScript 技术栈"

[[news]]
date = "2026-03"
content = "参与的第二篇论文进入框架阶段（三作）"

[[news]]
date = "2025-12"
content = "第一篇合作论文进入修改阶段（四作）"

[[news]]
date = "2025-09"
content = "进入成都中医药大学医学信息工程专业，加入中医药溯源团队担任副教授助理"
